apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres_service
spec:
  selector:
    app: postgres_pod
  type: NodePort
  ports:
  - port: 8080
    targetPort: 5432
    protocol: TCP  
