apiVersion: v1
kind: Service
metadata:
  name: psqlcli
  labels:
    app: psql_service
spec:
  selector:
    app: psqlcli_pod
  type: NodePort
  ports:
  - port: 8081
    targetPort: 5433
    protocol: TCP  
